### ISSUE TITLE
ODT template field not change

### ISSUE THREAD

**Issue by abraham63** [ATM-Consulting/dolibarr_module_of#64]
Hello,

I try to add some field in a new odt template for orderfab ticket.

I had a block with this content [societe] to display the client name but it's keep display [societe] instead of the content. 
But the var contain something in function $TBS->render($locationTemplate, ...) of fiche_if.php file.

Why it's not replace ?

Moreover, my company logo doesn't appear at the top of the document (with the exemple odt file available in this repo)

Thanks for help

**Comment by atm-gauthier** [comment]
Hello @abraham63 ,

I just made a fix for the logo, which should appear if you print OF file with default odt template.
For [societe] tag, you could try to remove and rewrite it.
Sometimes TBS engine doesn't work if tag text is custom (with a color or a different police).

**Comment by abraham63** [comment]
Thanks for the reply. It's work well now.

Another little problem. I can't generate PDF file. I have ErrorFileDoesNotExists: OF16(27_08_2018)/OF00016.pdf execption.

Where is the conversion define (the function) ? I have LibreOffice on my system (mac) but don't know if it's effective on my localhost server.

Thanks

**Comment by atm-gauthier** [comment]
I think LibreOffice doesn't work as it should.
We created a webservice to convert odt in pdf online.
You can try to add following hidden configuration in menu Home->Setup->Other setup :
Name : ABRICOT_CONVERTPDF_USE_ONLINE_SERVICE
Value : http://pdfservice.atm-consulting.fr/pdf.php

**Comment by abraham63** [comment]
work like a charm.
Thanks
