### ISSUE TITLE
API

### ISSUE THREAD

**Issue by abraham63** [ATM-Consulting/dolibarr_module_of#65]
Bonjour,

J'essai d'ajouter une petite API assez simple au module mais j'ai des soucis pour la connexion à la base de donnée

Voici l'erreur : 
`PDO DB ErrorConnexion : SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) ( mysql:dbname=dolibarr;host=localhost;port=8889;charset=latin1 - root ) < L. 118 Modof__construct() dans /Applications/MAMP/htdocs/doli/htdocs/includes/restler/framework/Luracast/Restler/Scope.php < L. 1047 Luracast\Restler\Scopeget() dans /Applications/MAMP/htdocs/doli/htdocs/includes/restler/framework/Luracast/Restler/Restler.php < L. 304 Luracast\Restler\Restlercall() dans /Applications/MAMP/htdocs/doli/htdocs/includes/restler/framework/Luracast/Restler/Restler.php < L. 230 Luracast\Restler\Restlerhandle() dans /Applications/MAMP/htdocs/doli/htdocs/api/index.php`

alors que cela marche bien via les pages de Dolibarr.

Je penche donc pour un probleme d'authentification ?.
Des idées ?

Le code de l'API 
```
function __construct()
    {
    global $user, $db, $conf, $langs;
  	$this->PDOdb=new TPDOdb;
    $this->assetof = new TAssetOF;
    }

    /**
     * Get Properties of Fabrication order object
     *
     * Get details of an Fabrication order

     * @param 	int 	$id ID of of
     * @return 	array|mixed data without useless information
     *
     * @throws 	RestException
     */
    function get($id){
			  $result = $this->assetof->load($this->PDOdb,$id);
				if( ! $result ) {
						throw new RestException(404, 'OF not found');
				}
				return $this->assetof;

    }
```

avec l'include de ordre_fabrication_asset.class.php

Merci

**Comment by atm-gauthier** [comment]
Bonjour,
Difficile de savoir ce qui se passe avec uniquement ce bout de code.
Les pages de Dolibarr incluent 2 fichiers essentiels qui sont le main.inc.php et le master.inc.php dans lesquels sont instanciés les accès en base de données à l'aide du fichier de conf de Dolibarr.

**Comment by abraham63** [comment]
Merci j'ai pu avancer un peu. J'arrive à me connecter (des paramètres qui ne passaient correctement pas au constructeur du connecteur).

Mais maintenant je ne peux pas effectuer certaines opérations. Par exemple si je veux modifier une ligne de l'OF (des produits à fabriquer) en changeant simplement la quantité je me retrouve avec cet access_denied alors que je peux modifier l'objet OF global sans problème.

Comment est faite la gestion de droit ?

**Comment by atm-gauthier** [comment]
Bonjour,

Comme expliqué dans ma précédente note, il est difficile de vous aider sans avoir le détail de ce qui est attendu et de votre code.
Nous avons la possibilité de vous aider dans votre développement, ou même de le faire pour vous, mais ceci est une prestation payante.
Si vous souhaitez entrez en contact avec nous pour mettre en place un projet, faites moi le savoir pour que je puisse vous mettre en relation avec notre service commercial.

Bonne journée,
Gauthier.
