### ISSUE TITLE
Compat issues

### ISSUE THREAD

**Issue by cfoellmann** [ATM-Consulting/dolibarr_module_of#94]
Hi @atm-greg and others form @atm-consulting,

I have two minor issues with (all) ATM modules.

First:
`set_time_limit(120);` the function is widely considered risky so it results in warnings due to blocked functions.
My suggestion is:
`@set_time_limit(120);` to silence the warning

Second:
The config.default.php start with
```php
	if(is_file('../main.inc.php'))$dir = '../';
	else  if(is_file('../../../main.inc.php'))$dir = '../../../';
	else  if(is_file('../../../../main.inc.php'))$dir = '../../../../';
	else  if(is_file('../../../../../main.inc.php'))$dir = '../../../../../';
	else $dir = '../../';
```
which results in php notices when the module is in the common path `htdocs/custom/modulename`.
My suggestion is change to:
```php
	if(is_file('../main.inc.php'))$dir = '../';
	else  if(is_file('../../main.inc.php'))$dir = '../../'; // add this line
	else  if(is_file('../../../main.inc.php'))$dir = '../../../';
	else  if(is_file('../../../../main.inc.php'))$dir = '../../../../';
	else  if(is_file('../../../../../main.inc.php'))$dir = '../../../../../';
	else $dir = '../../';
```

What do you guys think?

**Comment by atm-john** [comment]
`if(is_file('../main.inc.php'))$dir = '../';
	else  if(is_file('../../../main.inc.php'))$dir = '../../../';
	else  if(is_file('../../../../main.inc.php'))$dir = '../../../../';
	else  if(is_file('../../../../../main.inc.php'))$dir = '../../../../../';
	else $dir = '../../';`

**Comment by atm-ph** [comment]
First issue : I think you can add `@`
second issue : I don't understand why you got notices for this, but you can add an `else if` statement

**Comment by cfoellmann** [comment]
The issue with the path is the following warning:
```
Warning: is_file(): open_basedir restriction in effect. File(../../../../main.inc.php) is not within the allowed path(s): (/home/xxx/xxx/dolibarr-testing02:/var/lib/php/session:/tmp) in /home/xxx/xxx/dolibarr-testing02/htdocs/custom/of/config.default.php on line 6
```
since the "real" path depth is skipped in my case (the most common) all steps after that try to go where they are not supposed to. In my opinion adding the line make the code more functional.
